### ISSUE TITLE
Add instructions for how to get a RedisCloud URL

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-redis#20]
Add next section to: https://github.com/dwyl/learn-redis#which-redis-as-a-service-heroku-addon
relates to: https://github.com/dwyl/hapi-socketio-redis-riot-chat-example/issues/7
cc: @rjmk 

In your heroku app, click on `Resources`
![learn-redis-01-find-addon](https://cloud.githubusercontent.com/assets/194400/9439757/c51197a4-4a61-11e5-82f6-c84e84a55437.png)

Select RedisCloud Free plan and add to your heroku app:
![learn-redis-02-select-rediscloud](https://cloud.githubusercontent.com/assets/194400/9439767/d53c1b5e-4a61-11e5-8874-3c6418700166.png)

Confirm its been enabled
![learn-redis-03-enabled](https://cloud.githubusercontent.com/assets/194400/9439776/e58c1248-4a61-11e5-817b-7d865a2cf7ef.png)

Get the `REDISCLOUD_URL` Config Variable so you can use it:
![learn-redis-04-config-vars](https://cloud.githubusercontent.com/assets/194400/9439779/ed4d12e8-4a61-11e5-9d05-ff4ad322bb0e.png)

**Comment by iteles** [comment]
:+1:
